### PR TITLE
add copy clipboard for hex keys

### PR DESCRIPTION
**Pull request by wolftrax5**
#364 
I put my solution if it's relevant or the community agrees to add,the idea is to help the user who programs the device

Following the interface and to add may format to copy add a menu material with different options
a tooltip with description, and hide or show depend on the user

### CODE REVIEW

**Comment by wolftrax5** [comment]
The navigation.clipboard are currently supported for may browsers https://caniuse.com/#search=clipboard

**Comment by sabas1080** [comment]
I love this feature! Thanks!

**Comment by brocaar** [comment]
Looks great! Looking forward to merge this!

Two comments:

* Maybe it is better to rename the Clean option to "HEX string", so that the options become "Hex String" and "Hex Array"?
* When hovering the first option, the tooltip is hiding the second option. I'm not sure if a tooltip would be required in this case. Personally I think it looks cleaner without.

**Comment by wolftrax5** [comment]
It's OK @brocaar, I was thinking the same about tooltip, let me fix that, and do you think its necessary another format?

**Comment by wolftrax5** [comment]
> Looks great! Looking forward to merge this!
> 
> Two comments:
> 
> * Maybe it is better to rename the Clean option to "HEX string", so that the options become "Hex String" and "Hex Array"?
> * When hovering the first option, the tooltip is hiding the second option. I'm not sure if a tooltip would be required in this case. Personally I think it looks cleaner without.

these changes are now applied

**Comment by brocaar** [comment]
Thanks @wolftrax5 :+1: I have been on vacation. Will review your changes in the next days.

**Comment by wolftrax5** [comment]
It's ok, you really need the vacation for this excellent work(code)

**Comment by brocaar** [comment]
Works great :+1:

**Pull request merged**
