### PR TITLE
Node search

### PR DESCRIPTION
**Pull request by iegomez**
This is the node search enhancement discussed in #120, considering the search query optimizations and an explicit search button instead of auto-search. The fork is fully up to date with the latest master branch.

### CODE REVIEW

**Comment by brocaar** [comment]
Thanks @iegomez!

A couple of comments:
* To add the index, the user needs to setup an extra plugin. Would there be a way to avoid this? That way users are able to upgrade without any additional steps :-)

E.g. there are already a couple of fields where you can search on username (prefix). We could maybe apply the same to the device table? I did a quick test with the following:

```sql
create index idx_node_dev_eui_prefix on node (dev_eui, encode(dev_eui, 'hex') varchar_pattern_ops);
drop index test_index;
explain select * from node where encode(dev_eui, 'hex') like '01%';
```

See also: https://github.com/brocaar/lora-app-server/blob/master/internal/storage/user.go#L296 and https://github.com/brocaar/lora-app-server/blob/master/migrations/0014_users_and_application_users.sql#L14

Btw: In the code I'm using this in the query `where ($3 != '' and username like $3) or ($3 = '')`. I'm not sure if this is strictly required (e.g. when there is nothing to search on, the first block would evaluate to true as it does not have to hit the index for comparison). 

* There might be some changes you still need to make in the tests as the tests are currently failing

* Please note that the migrations both have a `-- +migrate Up` and `-- +migrate Down` section!

**Comment by iegomez** [comment]
Hi, @brocaar!
Regarding the pg_trgm extension, as far as I know there is no way to bypass it, nor install it within a migration, it needs to be created as a superuser directly in the DB, which was also my concern on the discussion at #120. If you think prefixes are good enough for searching purposes, then let's go with that approach. I'll also add the empty string check you mention.

Btw, I think there's a little inconsistency in your users code: though you only match prefixes on the GetUsers function, you match any substring at the GetUsersCount function at https://github.com/brocaar/lora-app-server/blob/master/internal/storage/user.go#L279, which would not only incur on a seq scan, but also give a different users count than GetUsers. Am I missing something there?

Finally, my bad with not dropping the index at migrate down, I just forgot to put it there on the updated version. I think that the failed test has to with this also.

**Comment by iegomez** [comment]
@brocaar, I made all the changes and everything seems to be ok, but checks fail. The odd thing is that when checking the details in the travis build, there's no failure in any test. Storage user checks -which should be the last before migrations- do pass, and then it just exits with error 2. I'm not sure what's going on there, do you have any clues?

**Comment by brocaar** [comment]
Cheers! Will test it tomorrow and then merge into `master` :-)

**Comment by iegomez** [comment]
Nice! I just added a little fix (I accidentally erased a couple of lines before), tested it locally and search was working fine.
Besides that, any comments about the users search that I mentioned? Is there a reason for the double wildcard on GetUsersCount? If not, let me know to include that fix too.

**Comment by brocaar** [comment]
Just tested it and it works great :-) I have a few more tiny comments, then it is good to be merged into master :-) I'll make the comments inline.

**Comment by brocaar** [comment]
> Btw, I think there's a little inconsistency in your users code: though you only match prefixes on the GetUsers function, you match any substring at the GetUsersCount function at https://github.com/brocaar/lora-app-server/blob/master/internal/storage/user.go#L279, which would not only incur on a seq scan, but also give a different users count than GetUsers. Am I missing something there?

You're right. If you could fix this (I think remove the prefix `%` should do it), that would be welcome :-)

**Comment by iegomez** [comment]
I just added that fix to the PR.

**Comment by brocaar** [comment]
@iegomez, did you see my other (inline) comments?

**Comment by iegomez** [comment]
No, sorry, I didn't get any notifications and didn't see any in the files changed tab. Where should I look?

**Comment by brocaar** [comment]
Yo should see them here in the conversation tab (scroll a bit up) and as inline comments here: https://github.com/brocaar/lora-app-server/pull/162/files.

**Comment by iegomez** [comment]
I think they are not visible to everyone right now, and I wasn't notified of any comments (which should normally happen). From github docs:

> Before you submit your review, your line comments are pending and only visible to you. You can edit pending comments anytime before you submit your review. To cancel a pending review, including all of its pending comments, scroll down to the end of the timeline on the Conversation tab, then click Cancel review.

Anyway, I made 3 little changes that could be related to your comments:

1) pageSize was set to 2 instead of 20 on ListNodes.js. I changed it back.
2) The installations docs mentioned connecting to the DB, which was necessary to install the pg_trgm extension. I removed it.
3) The search indexes migration lacked a final new line. I added it.

If there's anything that I missed, please submit your review so I can see the comments, or just comment here.

**Comment by brocaar** [comment]
Ah, that explains. They recently updated the code-review. Wasn't aware that I needed to do a final submit of it. Thanks for mentioning :-)

**Comment by brocaar** [comment]
Thanks for all the work @iegomez, your changes have been merged 👍 I've made one additional change, see f122d5b0a4760759fb92120d239c8328719daeaa. With this change the search form is moved to the panel heading.

**Comment by iegomez** [comment]
Great! Hope it helps.

**Pull request merged**
